### ISSUE TITLE
Crash after updating compose libraries

### ISSUE THREAD

**Issue by medico-kmdev** [yogeshpaliyal/Speld#8]
Device - one plus 10r
Android - 13

    const val composeUi = "1.4.3"
    const val composeFoundation = "1.4.3"
    const val composeCompiler = "1.4.7"
    
    `FATAL EXCEPTION: main
                                                                                                    Process: com.zealsoftsol.medico.dev, PID: 6936
                                                                                                    java.lang.IllegalStateException: Expected BringIntoViewRequester to not be used before parents are placed.
                                                                                                    	at androidx.compose.foundation.gestures.ContentInViewModifier.calculateRectForParent(ContentInViewModifier.kt:117)
                                                                                                    	at androidx.compose.foundation.relocation.BringIntoViewResponderModifier$bringChildIntoView$parentRect$1.invoke(BringIntoViewResponder.kt:152)
                                                                                                    	at androidx.compose.foundation.relocation.BringIntoViewResponderModifier$bringChildIntoView$parentRect$1.invoke(BringIntoViewResponder.kt:152)
                                                                                                    	at androidx.compose.foundation.relocation.AndroidBringIntoViewParent.bringChildIntoView(BringIntoViewResponder.android.kt:43)
                                                                                                    	at androidx.compose.foundation.relocation.BringIntoViewResponderModifier$bringChildIntoView$2$2.invokeSuspend(BringIntoViewResponder.kt:171)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:57)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:240)
                                                                                                    	at android.os.Looper.loop(Looper.java:351)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8416)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
                                                                                                    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@16ff7b7, androidx.compose.runtime.BroadcastFrameClock@8b06b24, StandaloneCoroutine{Cancelling}@59ac68d, AndroidUiDispatcher@973b042]`

**Comment by TheEnsis** [comment]
I also found this error too

**Comment by yogeshpaliyal** [comment]
Will work on this ASAP

**Comment by medico-kmdev** [comment]
one simple change that worked for me was to request focus in onfocusChanged

`     OtpCell(
                modifier = cellModifier
                    .size(width = 45.dp, height = 45.dp)
                    .clip(MaterialTheme.shapes.large)
                    .background(
                        MaterialTheme.colors.primary.copy(alpha = 0.1f),
                        shape = RoundedCornerShape(3.dp)
                    )
                    .onFocusChanged {
                        focusRequester.requestFocus()
                    }
                    .clickable {
                        keyboard?.show()
                    },
                value = value.getOrNull(it),
                isCursorVisible = value.length == it,
                obscureText
            )`

**Comment by TheEnsis** [comment]
> one simple change that worked for me was to request focus in onfocusChanged
> 
> ` OtpCell( modifier = cellModifier .size(width = 45.dp, height = 45.dp) .clip(MaterialTheme.shapes.large) .background( MaterialTheme.colors.primary.copy(alpha = 0.1f), shape = RoundedCornerShape(3.dp) ) .onFocusChanged { focusRequester.requestFocus() } .clickable { keyboard?.show() }, value = value.getOrNull(it), isCursorVisible = value.length == it, obscureText )`

it work now!! Thank you.
